import React from 'react';
import { Document, Page, View, Text, StyleSheet, Svg, Path, renderToStream } from '@react-pdf/renderer';

// Track 2 — PDF Notes rendering. Pure-Node (no headless browser) via
// @react-pdf/renderer, so it runs reliably on any Render tier. Built with
// React.createElement (the server has no JSX transpile step). The Eklavya logo
// is ported directly from EklavyaLogo.jsx's inline SVG → native <Svg>/<Path>, so
// it stays crisp at any print/zoom DPI and there's no separate PNG to drift.
const e = React.createElement;

// Logo (vector) — paths copied from client/src/components/EklavyaLogo.jsx.
function Logo({ size = 30 }) {
  return e(
    Svg,
    { width: size, height: size, viewBox: '0 0 120 120' },
    e(Path, { d: 'M56 46C51 28 36 14 30 6C44 4 58 18 56 46Z', fill: '#2F6B3A' }),
    e(Path, { d: 'M64 46C69 28 84 14 90 6C76 4 62 18 64 46Z', fill: '#2F6B3A' }),
    e(Path, { d: 'M60 40V68', stroke: '#2F6B3A', strokeWidth: 4.5, strokeLinecap: 'round' }),
    e(Path, { d: 'M60 88C38 76 16 78 8 88C24 104 50 102 60 88Z', fill: '#2F6B3A' }),
    e(Path, { d: 'M60 88C82 76 104 78 112 88C96 104 70 102 60 88Z', fill: '#2F6B3A' }),
    e(Path, { d: 'M60 76C40 66 22 68 15 76C28 90 48 88 60 76Z', fill: '#E07A3E' }),
    e(Path, { d: 'M60 76C80 66 98 68 105 76C92 90 72 88 60 76Z', fill: '#E07A3E' }),
    e(Path, { d: 'M60 64C44 56 30 58 24 64C34 76 50 74 60 64Z', fill: '#66BB6A' }),
    e(Path, { d: 'M60 64C76 56 90 58 96 64C86 76 70 74 60 64Z', fill: '#66BB6A' })
  );
}

const styles = StyleSheet.create({
  page: { paddingTop: 66, paddingBottom: 52, paddingHorizontal: 48, fontSize: 11, color: '#1F2A1F', lineHeight: 1.5, fontFamily: 'Helvetica' },
  header: { position: 'absolute', top: 20, left: 48, right: 48, flexDirection: 'row', alignItems: 'center' },
  brandText: { marginLeft: 8 },
  brandName: { fontSize: 13, fontFamily: 'Helvetica-Bold', color: '#2F6B3A', letterSpacing: 1 },
  brandTagline: { fontSize: 7, color: '#E07A3E' },
  headerRule: { position: 'absolute', top: 52, left: 48, right: 48, borderBottomWidth: 1, borderBottomColor: '#E4DAC5' },
  title: { fontSize: 20, fontFamily: 'Helvetica-Bold', color: '#1F2A1F', marginBottom: 3 },
  subtitle: { fontSize: 10, color: '#6B6357', marginBottom: 14 },
  section: { marginBottom: 12 },
  heading: { fontSize: 13, fontFamily: 'Helvetica-Bold', color: '#2F6B3A', marginBottom: 5 },
  bulletRow: { flexDirection: 'row', marginBottom: 3 },
  bulletDot: { width: 12, color: '#2F6B3A' },
  bulletText: { flex: 1 },
  termRow: { marginBottom: 4 },
  term: { fontFamily: 'Helvetica-Bold' },
  footer: { position: 'absolute', bottom: 22, left: 48, right: 48, flexDirection: 'row', justifyContent: 'space-between' },
  footerText: { fontSize: 8, color: '#9A9384' },
  pageNum: { fontSize: 8, color: '#9A9384' }
});

function NotesDocument(notes) {
  const { title, subject, topic, sections = [], keyTerms = [] } = notes;
  const subline = [subject, topic].filter(Boolean).join('  ·  ');

  return e(
    Document,
    { title: title || 'Eklavya Study Notes', author: 'Project Eklavya' },
    e(
      Page,
      { size: 'A4', style: styles.page },
      // Fixed header (repeats on every page)
      e(View, { fixed: true, style: styles.header },
        e(Logo, { size: 30 }),
        e(View, { style: styles.brandText },
          e(Text, { style: styles.brandName }, 'EKLAVYA'),
          e(Text, { style: styles.brandTagline }, 'Ek Shikshak, Har Vidhyarthi')
        )
      ),
      e(View, { fixed: true, style: styles.headerRule }),

      // Title block
      e(Text, { style: styles.title }, title || 'Study Notes'),
      subline ? e(Text, { style: styles.subtitle }, subline) : null,

      // Sections
      ...sections.map((s, i) => e(View, { key: `s${i}`, style: styles.section },
        s.heading ? e(Text, { style: styles.heading }, s.heading) : null,
        ...(s.points || []).map((p, j) => e(View, { key: `p${j}`, style: styles.bulletRow },
          e(Text, { style: styles.bulletDot }, '•'),
          e(Text, { style: styles.bulletText }, p)
        ))
      )),

      // Key terms
      keyTerms.length > 0
        ? e(View, { style: styles.section },
            e(Text, { style: styles.heading }, 'Key Terms'),
            ...keyTerms.map((k, i) => e(Text, { key: `t${i}`, style: styles.termRow },
              e(Text, { style: styles.term }, `${k.term}: `),
              k.definition
            ))
          )
        : null,

      // Fixed footer with page numbers
      e(View, { fixed: true, style: styles.footer },
        e(Text, { style: styles.footerText }, 'Generated by Eklavya'),
        e(Text, { style: styles.pageNum, render: ({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}` })
      )
    )
  );
}

// Returns a Node readable stream of the rendered PDF (for streaming download).
export function renderNotesPdf(notes) {
  return renderToStream(NotesDocument(notes));
}
