import dotenv from 'dotenv'; dotenv.config();
const B='http://127.0.0.1:5000/api';
const E=process.env.ADMIN_EMAIL, P=process.env.ADMIN_PASSWORD, C=process.env.ADMIN_SECURITY_CODE;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const login=async(b)=>{for(let i=0;i<25;i++){try{const r=await fetch(B+'/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});return {s:r.status,b:await r.json().catch(()=>({}))};}catch{await sleep(1000);}}throw new Error('unreachable');};
let ok=true;const A=(c,l)=>{if(!c)ok=false;console.log((c?'✓':'✗ FAIL')+' '+l);};
const good=await login({email:E,password:P,securityCode:C});
A(good.s===200 && good.b.user?.role==='admin','correct plaintext creds → 200 admin');
A((await login({email:E,password:'wrong',securityCode:C})).s===401,'wrong password → 401');
A((await login({email:'nope@x.com',password:P,securityCode:C})).s===401,'wrong email → 401');
A((await login({email:E,password:P,securityCode:'nope'})).s===401,'wrong code → 401');
console.log('\nadmin login now uses: '+E+' / '+P+' / '+C);
console.log(ok?'ALL PASS ✓':'FAIL ✗');
