import mongoose from 'mongoose';
import { hindiQuestionFields } from './writtenFields.js';
import { BOARDS } from '../config/taxonomy.js';

// Workstream I — a question that is EITHER extracted from a real past paper OR
// generated by AI in the style of one. Never something in between.
//
// ── I0: WHY THE SOURCE FIELD HAS NO DEFAULT ─────────────────────────────────
//
// A student revising for a board exam who practises AI-generated questions in the
// belief that they are real past papers is being actively misled, and cannot
// possibly detect it — the whole reason to practise past papers is that they are
// evidence of what the board actually asks. A generated question that looks like a
// 2023 CBSE question is not weaker evidence; it is FALSE evidence.
//
// So the distinction is structural rather than a convention:
//
//   • `source` is required with NO DEFAULT. A question saved without one fails
//     validation. A default — either value — would mean that the failure mode of
//     forgetting to set it is silently mislabelled content, and the safer-looking
//     choice ('generated') is not actually safe: it would quietly relabel real
//     extracted questions and lose their paper.
//   • 'pyq' REQUIRES paperId, board and year. It cannot exist without a provenance
//     record pointing at the PDF it came from.
//   • 'generated' FORBIDS year, board and paperId. Not "leaves them blank" —
//     forbids, because a year on a generated question is the single field that turns
//     it into a counterfeit past paper, and the UI renders any year it is given.
//
// The pre-validate hook below enforces both directions. The CI invariant in
// ci-invariants.mjs enforces the third rule: nothing outside the import pipeline is
// allowed to WRITE source: 'pyq' in the first place.

const pyqQuestionSchema = new mongoose.Schema({
  // ── The distinction ───────────────────────────────────────────────────────
  source: {
    type: String,
    enum: ['pyq', 'generated'],
    required: [true, 'PYQ_SOURCE_REQUIRED'],
    // NO DEFAULT. See the header. Do not add one.
    default: undefined
  },

  // ── Real-paper provenance. 'pyq' only. ────────────────────────────────────
  //
  // Each of these three carries BOTH directions of the rule: `required` when the
  // source is 'pyq', and a `validate` that refuses it outright when the source is
  // 'generated'.
  //
  // They are field validators rather than a single pre('validate') hook for a reason
  // that is easy to get wrong: Mongoose does NOT run pre-validate MIDDLEWARE during
  // `validateSync()`. A hook-based version of this rule passes every unit check that
  // uses validateSync and only fires on a real `.save()` — so the guard reads as
  // enforced while a test proving it can be written that always passes. Field
  // validators run in both paths.
  paperId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'PastPaper',
    required: function () { return this.source === 'pyq'; },
    validate: {
      validator: function (v) { return !(this.source === 'generated' && v); },
      message: 'GENERATED_QUESTION_MUST_NOT_HAVE_PAPER'
    }
  },
  board: {
    type: String,
    enum: { values: [...BOARDS, null], message: 'PYQ_BOARD_INVALID' },
    required: function () { return this.source === 'pyq'; },
    default: null,
    validate: {
      validator: function (v) { return !(this.source === 'generated' && v); },
      message: 'GENERATED_QUESTION_MUST_NOT_HAVE_BOARD'
    }
  },
  year: {
    type: Number,
    required: function () { return this.source === 'pyq'; },
    default: null,
    // THE field that turns a generated question into a counterfeit past paper: the
    // "CBSE 2023 · Q14" label is built from it, so a year is the whole forgery.
    validate: {
      validator: function (v) {
        return !(this.source === 'generated' && v !== null && v !== undefined);
      },
      message: 'GENERATED_QUESTION_MUST_NOT_HAVE_YEAR'
    }
  },

  // ── Identity within the paper ─────────────────────────────────────────────
  // sectionName mirrors PastPaper.sections[].name. questionNumber is the number AS
  // PRINTED ("14", "14(a)") — a string, because exam papers number questions in
  // ways integers cannot hold, and because the label a student sees must match the
  // label on the paper in front of them.
  sectionName: { type: String, default: '' },
  // Denormalised from the section so practice mode can filter by discipline without
  // joining back to the paper on every query. '' when the paper is not
  // discipline-sectioned. See PastPaper.sections[].discipline for why both exist.
  sectionDiscipline: { type: String, default: '' },
  questionNumber: { type: String, default: '' },
  marks: { type: Number, default: 0 },

  // ── Internal choice ("Q31 ... OR ... ") ───────────────────────────────────
  //
  // Indian board papers routinely print two alternatives under ONE question number
  // and instruct the student to attempt only one. That is not two questions and it
  // is not one question either — it is a CHOICE, and it has to be modelled as one.
  //
  // This was originally papered over: the schema comment above used to give
  // `"31 OR"` as an example questionNumber, which is the phenomenon spotted and then
  // encoded as a string suffix. That representation cannot answer any of the
  // questions the app actually needs to ask — how many questions does this paper
  // have, how many marks are available, which alternative did the student attempt —
  // and it silently inflates the question count, which is one of the causes of the
  // 71-from-39 over-extraction measured on a real paper.
  //
  // Each alternative is its own document (so it has its own text, options, figure
  // and translation) and they are tied together by a shared `choiceGroup`:
  //   • `choiceGroup` — stable key shared by alternatives, scoped to the paper.
  //     '' means this question has no alternative, which is the common case.
  //   • `choiceIndex` — 0 for the alternative printed first, 1 for the one after
  //     the "OR", and so on.
  //
  // Consequences that callers MUST respect, because getting them wrong is how a
  // paper reports 45 questions and 95 marks when it has 39 and 80:
  //   • Counting questions means counting DISTINCT choice groups, not documents.
  //   • A choice group contributes its marks to `marksAvailable` exactly ONCE.
  // Both are centralised in `countChoiceGroups()` / `availableMarks()` below rather
  // than reimplemented per call site.
  choiceGroup: { type: String, default: '' },
  choiceIndex: { type: Number, default: 0 },

  // ── Sub-parts ("Q1. Read the passage... (i)... (ii)...") ─────────────────
  //
  // A DIFFERENT relationship from choiceGroup, and confusing the two is the most
  // damaging error this parser can make. Both group rows under one printed number:
  //
  //   choiceGroup  — "attempt any ONE of these"      (the paper prints OR / अथवा)
  //   parentKey    — "answer ALL of these"           (no OR; they are parts)
  //
  // Getting it backwards tells a student to attempt one part of a compulsory
  // question. That is a wrong INSTRUCTION on a real paper, which is worse than a
  // miscount — a miscount is visible to an admin reviewing a draft; a wrong rubric
  // reads as the paper's own.
  //
  // Observed in three different printed forms, all handled the same way:
  //   English Cl10   Q1 stimulus + parts numbered I, II, III...
  //   Social Science Q17A / Q17B          (letter suffix)
  //   Physics Cl12   (I) / (II) inline    (was being folded as OR — the bug)
  //
  // COUNTING AND MARKS both key off this:
  //   • A container plus its parts is ONE question to a student. That is what
  //     reconciles a 39-row English parse back to the 11 the paper states.
  //   • Marks sum over PARTS ONLY. The container reprints the total of its parts
  //     ("Q1 ... 10 marks"), so counting both double-counts — which is exactly how
  //     an 80-mark paper summed to 110.
  parentKey: { type: String, default: '' },
  // The stimulus/instruction row that introduces the parts. Carries the printed
  // total in `marks` for display, but is EXCLUDED from mark summation.
  isContainer: { type: Boolean, default: false },
  partLabel: { type: String, default: '' },   // 'I', 'A', '(ii)' — as printed

  // Set when the paper's own layout did not make it clear whether rows are
  // alternatives or parts. Deliberately NOT guessed: an ambiguous question flagged
  // for review is fine, a confidently wrong instruction is not.
  partsAmbiguous: { type: Boolean, default: false },

  // How the parts of this family relate, and the PRINTED WORDS that decided it.
  // Kept as a field rather than collapsed into `partsAmbiguous` because the review UI
  // has to show an admin *why*: "choose-one, because 'OR' is printed between them" is
  // checkable against the page; a bare boolean is not.
  //
  // 'unclear' is scored as all-required. The two errors are not symmetric:
  //   • a real choice treated as required  -> the student answers both, wasting time
  //   • required parts treated as a choice -> the student skips one and LOSES MARKS
  //     on a compulsory question, because the app told them to.
  // Only the losing-marks direction is unrecoverable, so abstention falls the other way.
  partsRelation: {
    type: String,
    enum: ['all-required', 'choose-one', 'unclear'],
    default: 'all-required',
  },
  partsRelationEvidence: { type: String, default: '' },

  // ── Content ───────────────────────────────────────────────────────────────
  // `questionText` (not `question`) so translateQuestionsArray() and the existing
  // narration paths work on these unchanged.
  questionText: { type: String, required: true },
  options: { type: [String], default: [] },        // empty for non-MCQ
  correctIndex: { type: Number, default: null },   // MCQ only
  correctAnswer: { type: String, default: '' },    // non-MCQ model answer
  explanation: { type: String, default: '' },

  // ── Figures ───────────────────────────────────────────────────────────────
  // For 'pyq' this is an IMAGE CROPPED FROM THE PDF, stored through the existing
  // Cloudinary path. It is never generated and never regenerated: for a geometry or
  // circuit question the specific figure IS the question, and a plausible
  // substitute is a different question wearing the same number.
  //
  // For 'generated' the existing SVG pipeline applies instead and writes
  // `diagramSvg` — a different field on purpose, so the two can never be confused
  // at a call site or silently fall back to one another.
  diagramUrl: {
    type: String,
    default: '',
    // An extracted image on a generated question means a real paper's figure has
    // been attached to invented text — the worst version of the conflation, because
    // the figure is genuine and lends the text its authority.
    validate: {
      validator: function (v) { return !(this.source === 'generated' && v); },
      message: 'GENERATED_QUESTION_MUST_NOT_HAVE_EXTRACTED_FIGURE'
    }
  },
  diagramPublicId: { type: String, default: '' },
  // The rendered source page this question was parsed from. Admin-only context for
  // the review screen: it is what an admin looks at to check a figure was assigned to
  // the right question, and what they snip from when the parse missed one. Never
  // served to students — only `diagramUrl` reaches them.
  sourcePageUrl: { type: String, default: '' },
  // Admin-entered, NOT AI-generated. Read-aloud depends on it, and a confidently
  // wrong description of a real exam figure is worse than no description.
  diagramAlt: { type: String, default: '' },
  diagramAltHindi: { type: String, default: '' },

  // Set by the parser when the question text REFERS to a figure ("in the figure
  // below", "from the given circuit"). A question with figureExpected and no
  // diagramUrl is unanswerable, so it blocks publication of its paper rather than
  // shipping figureless — the existing orphan-reference guard, except that here it
  // cannot be resolved by dropping the figure reference.
  figureExpected: { type: Boolean, default: false },

  // Generated questions only — the existing SVG pipeline's output.
  diagramSvg: {
    type: String,
    default: '',
    validate: {
      validator: function (v) { return !(this.source === 'pyq' && v); },
      message: 'PYQ_QUESTION_MUST_NOT_HAVE_GENERATED_FIGURE'
    }
  },

  ...hindiQuestionFields,

  createdAt: { type: Date, default: Date.now }
});

// Practice/exam queries select by paper, and the year filter runs over papers rather
// than questions, so paperId + sectionName is the shape that actually gets asked.
pyqQuestionSchema.index({ paperId: 1, sectionName: 1 });
pyqQuestionSchema.index({ source: 1 });

/**
 * Is this question publishable? A real-paper question whose figure could not be
 * extracted is NOT: the text says "in the figure below" and there is no figure.
 * Exported so the publish route and the admin review UI apply one rule.
 */
export function questionBlocksPublication(q) {
  return q.source === 'pyq' && q.figureExpected === true && !q.diagramUrl;
}

/**
 * The key a question counts under. An alternative shares its group's key, so two
 * halves of an "OR" count once.
 *
 * The fallback chain matters and is the reason this is a function rather than
 * `q.choiceGroup || q._id`. These helpers run over BOTH persisted documents and
 * raw parser output, and parser output has no `_id` — an earlier version returned
 * `String(q._id)`, so every non-choice question keyed to the literal string
 * `"undefined"`, collapsed into one bucket, and a 39-question paper counted as 5.
 * A distinctness helper that silently makes everything identical is worse than no
 * helper, so the last resort is the OBJECT ITSELF: Sets and Maps key it by
 * identity, which is exactly "this entry is its own question" and can never
 * collide.
 */
export function choiceKeyOf(q) {
  if (q.choiceGroup) return q.choiceGroup;
  if (q._id) return String(q._id);
  const printed = `${q.sectionName || ''}|${q.questionNumber || ''}`;
  return printed === '|' ? q : printed;
}

/**
 * The key a row counts under as a QUESTION, the way a student would count.
 *
 * A container and its parts are one question; a set of OR alternatives is one
 * question; anything else is itself. `parentKey` wins over `choiceGroup` because a
 * container's parts may themselves offer an internal choice, and the outer container
 * is still the single thing the paper numbered.
 */
export function unitKeyOf(q) {
  if (q.parentKey) return q.parentKey;
  return choiceKeyOf(q);
}

/**
 * Questions as the PAPER counts them. This is the number that must match the
 * paper's own "this question paper contains N questions".
 */
export function countQuestionUnits(questions) {
  return new Set(questions.map(unitKeyOf)).size;
}

/**
 * How many QUESTIONS a set represents, as a student would count them — distinct
 * choice groups, not documents. This is the number that must match the paper's own
 * "this question paper contains N questions".
 */
export function countChoiceGroups(questions) {
  return new Set(questions.map(choiceKeyOf)).size;
}

/**
 * Marks a student can actually earn. A choice group contributes ONCE — its
 * alternatives are the same marks offered two ways, not two scoring opportunities.
 * Takes the max within a group, so a mis-parsed alternative with 0 marks cannot
 * silently deflate the paper's total.
 */
export function availableMarks(questions) {
  // CONTAINERS ARE EXCLUDED. A container reprints the total of its own parts
  // ("Q1 ... 10 marks" over parts worth 1+1+1+2+1+2+2), so adding both counts those
  // marks twice — measured on CBSE Class 10 English, where an 80-mark paper summed
  // to 110. Marks live on the leaves; the container's value is for display.
  const leaves = questions.filter((q) => !q.isContainer);

  const byGroup = new Map();
  for (const q of leaves) {
    // Within a genuine OR group the marks are offered ONCE, however many
    // alternatives there are — so max, not sum. Sub-parts are NOT a choice group,
    // so they fall through to their own keys and sum normally.
    const k = choiceKeyOf(q);
    byGroup.set(k, Math.max(byGroup.get(k) || 0, q.marks || 0));
  }
  return [...byGroup.values()].reduce((a, b) => a + b, 0);
}

/** Group questions by choice key, preserving paper order. */
export function groupByChoice(questions) {
  const groups = new Map();
  for (const q of questions) {
    const k = choiceKeyOf(q);
    if (!groups.has(k)) groups.set(k, []);
    groups.get(k).push(q);
  }
  // Alternatives ordered as printed, so "OR" reads in the paper's own order.
  for (const g of groups.values()) g.sort((a, b) => (a.choiceIndex || 0) - (b.choiceIndex || 0));
  return [...groups.values()];
}

export default mongoose.model('PyqQuestion', pyqQuestionSchema);
